{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[thread_id 139824471252992] 2024-05-27 12:06:37,279 - __main__ - INFO - Initalize...\n",
      "[thread_id 139824471252992] 2024-05-27 12:06:37,290 - utils.bigquery - INFO - Establish connection: dml-prod\n",
      "[thread_id 139824471252992] 2024-05-27 12:06:37,433 - utils.bigquery - INFO - Session created. Dml-Prod\n",
      "[thread_id 139824471252992] 2024-05-27 12:06:37,441 - utils.bigquery - INFO - Execute SQL on Dml-Prod:\n",
      "\n",
      "    -- Author: hexton.chan@hkexpress.com \n",
      "    -- Description: Get 7-day flight schedule IN which updated BY 7-day before departure, generate ASM_CON\n",
      "  SELECT\n",
      "    ID,\n",
      "    FLTID,\n",
      "    DATOP_CHN,\n",
      "    'OpmLegChangeAsmCon-' || FLTID || UPPER(FORMAT_DATETIME(\"-%y%m%d%H%M%S\",SRC_UPDATED_TIME))  AS correlationId,\n",
      "    'ASM' AS msgType,\n",
      "    --'UTC' AS timeZone,\n",
      "    --UPPER(FORMAT_DATETIME(\"%d%b%y\",CURRENT_DATETIME())) AS msgGenTime,\n",
      "    --'CON' AS msgSubType,\n",
      "    --FLIGHT_NO,\n",
      "    --UPPER(FORMAT_DATETIME(\"%d%b%y\",DATOP)) AS DATOP,\n",
      "    --ACTYPE,\n",
      "    --LONG_REG,\n",
      "    --SERVICE_TYPE_ID,\n",
      "    --DEPSTN,\n",
      "    --ARRSTN,\n",
      "    --FORMAT_DATETIME(\"%d%H%M\",STD) AS STD,\n",
      "    --FORMAT_DATETIME(\"%d%H%M\",STA) AS STA,\n",
      "    --SRC_CREATED_TIME,\n",
      "    --SRC_UPDATED_TIME,\n",
      "    'ASM\\r\\nUTC\\r\\n' ||\n",
      "    UPPER(FORMAT_DATETIME(\"%d%b%y\",DATOP)) || '001E001\\r\\n' ||\n",
      "    'CON\\r\\n' ||\n",
      "    ACOWN||SRC_FLIGHT_NO || '/' || UPPER(FORMAT_DATETIME(\"%d%b%y\",DATOP)) || '\\r\\n' ||\n",
      "    CASE\n",
      "      WHEN SERVICE_TYPE_ID = 1 THEN 'C'\n",
      "      WHEN SERVICE_TYPE_ID = 2 THEN 'D'\n",
      "      WHEN SERVICE_TYPE_ID = 3 THEN 'E'\n",
      "      WHEN SERVICE_TYPE_ID = 4 THEN 'F'\n",
      "      WHEN SERVICE_TYPE_ID = 5 THEN 'J'\n",
      "      WHEN SERVICE_TYPE_ID = 6 THEN 'K'\n",
      "      WHEN SERVICE_TYPE_ID = 7 THEN 'L'\n",
      "      WHEN SERVICE_TYPE_ID = 8 THEN 'M'\n",
      "      WHEN SERVICE_TYPE_ID = 9 THEN 'O'\n",
      "      WHEN SERVICE_TYPE_ID = 10 THEN 'P'\n",
      "      WHEN SERVICE_TYPE_ID = 11 THEN 'Q'\n",
      "      WHEN SERVICE_TYPE_ID = 12 THEN 'S'\n",
      "      WHEN SERVICE_TYPE_ID = 13 THEN 'T'\n",
      "      WHEN SERVICE_TYPE_ID = 14 THEN 'X'\n",
      "      WHEN SERVICE_TYPE_ID = 15 THEN 'Z'\n",
      "      WHEN SERVICE_TYPE_ID = 16 THEN 'T'\n",
      "    ELSE\n",
      "    'J'\n",
      "  END\n",
      "    || ' ' ||\n",
      "    CASE\n",
      "      WHEN ACTYPE = 'A321' THEN '321'\n",
      "      WHEN ACTYPE = 'A320' THEN '320'\n",
      "      WHEN ACTYPE = 'A21N' THEN '32Q'\n",
      "    ELSE\n",
      "    ACTYPE\n",
      "  END\n",
      "    || ' . ' || LONG_REG || '\\r\\n' || DEPSTN || FORMAT_DATETIME(\"%d%H%M\",STD) || ' ' || ARRSTN || FORMAT_DATETIME(\"%d%H%M\",STA)|| '\\r\\n' AS payload\n",
      "  FROM\n",
      "    `dml-prod.ODS_FlightNet.M_FOC_LEGS`\n",
      "  WHERE\n",
      "    -- DateTime Conditions: Next 7-days' flight -- \n",
      "    DATE_DIFF(DATOP_CHN,CURRENT_DATE('Asia/Hong_Kong'), DAY) <= 7\n",
      "    AND DATE(DATOP_CHN) >= CURRENT_DATE('Asia/Hong_Kong') -- (Include Today)\n",
      "    -- DateTime Conditions -- \n",
      "    \n",
      "    -- Standard Conditions: Identify a vaild flight schedule --\n",
      "    AND DELETED IS FALSE\n",
      "    AND long_reg IS NOT NULL\n",
      "    AND ATA IS NULL\n",
      "    AND ATD IS NULL\n",
      "    AND TOFF IS NULL\n",
      "    AND TDWN IS NULL\n",
      "    AND SRC_Flight_no IS NOT NULL\n",
      "    AND FLTID IS NOT NULL\n",
      "    AND LEGNO IS NOT NULL\n",
      "    AND DATETIME_DIFF(DATETIME(STA), DATETIME(STD), MINUTE) > 0 \n",
      "    -- Standard Conditions --\n",
      "    \n",
      "    -- ASM_CON Conditions: Catch updates WITHIN 7-days before departure --\n",
      "    AND SRC_CREATED_TIME <> SRC_UPDATED_TIME\n",
      "    AND DATE(SRC_UPDATED_TIME) > (DATOP_CHN - 7) \n",
      "    -- ASM_CON Conditions --\n",
      "\n",
      "  ORDER BY\n",
      "    DATOP ASC\n",
      "\n",
      "  \n",
      "\n",
      "[thread_id 139824471252992] 2024-05-27 12:06:38,297 - utils.bigquery - INFO - SQL executed. Timelapsed: 0:00:00.247000\n",
      "[thread_id 139824471252992] 2024-05-27 12:06:39,616 - utils.bigquery - INFO - Retrieved 160 rows.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from dotenv import load_dotenv\n",
    "try:\n",
    "    load_dotenv(dotenv_path='/home/connectivity-checker/.env', override=True)\n",
    "except:\n",
    "    try:\n",
    "        load_dotenv()\n",
    "    except:\n",
    "        pass\n",
    "    \n",
    "from utils.logging import Logging\n",
    "from utils.mq import MQ\n",
    "from utils.bigquery import BigQuery\n",
    "\n",
    "logger = Logging(__name__).init()\n",
    "mq = MQ().from_json_config(os.environ.get('CONFIG_MQ'), 'ASM')\n",
    "bigquery_dml = BigQuery().connect(os.environ.get('SECRET_GSERVICE_DML'))\n",
    "\n",
    "from sqls.asm_con import sql\n",
    "\n",
    "r = bigquery_dml.select_rows_by_standard_sql(sql.get_select_msg_payload('dml-prod'))\n",
    "\n",
    "mq.set_message(r['payload'][0])\n",
    "mq.set_correlation_id(r['correlationId'][0])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[thread_id 139663934713856] 2024-05-24 18:14:38,740 - utils.mq - INFO - ==== [START] MQ Java Subprocess ====\n",
      "[thread_id 139663934713856] 2024-05-24 18:14:42,155 - utils.mq - INFO - [Success 0] Message: OpmLegChangeAsmCon-211255-240523142740 successfully sent to remote side.\n",
      "[thread_id 139663934713856] 2024-05-24 18:14:42,157 - utils.mq - CRITICAL - failed to get connect or send message\n",
      "com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ0018: Failed to connect to queue manager 'MQEXTT01' with connection mode 'Client' and host name 'externalmq-t0.ete.cathaypacific.com(1414)'.\n",
      "Check the queue manager is started and if running in client mode, check there is a listener running. Please see the linked exception for more information.\n",
      "\tat com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)\n",
      "\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)\n",
      "\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:448)\n",
      "\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)\n",
      "\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)\n",
      "\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)\n",
      "\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createConnection(JmsConnectionFactoryImpl.java:236)\n",
      "\tat com.ibm.mq.jms.MQConnectionFactory.createCommonConnection(MQConnectionFactory.java:6005)\n",
      "\tat com.ibm.mq.jms.MQQueueConnectionFactory.createQueueConnection(MQQueueConnectionFactory.java:136)\n",
      "\tat com.ibm.mq.jms.MQQueueConnectionFactory.createConnection(MQQueueConnectionFactory.java:209)\n",
      "\tat JmsClient.connect(JmsClient.java:75)\n",
      "\tat Main.main(Main.java:36)\n",
      "Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2393' ('MQRC_SSL_INITIALIZATION_ERROR').\n",
      "\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)\n",
      "\t... 10 more\n",
      "Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393;AMQ9204: Connection to host 'externalmq-t0.ete.cathaypacific.com(1414)' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2393],3=externalmq-t0.ete.cathaypacific.com(1414),5=RemoteTCPConnection.getNonFipsSocketFactory]\n",
      "\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13558)\n",
      "\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1426)\n",
      "\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1385)\n",
      "\tat com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377)\n",
      "\tat com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562)\n",
      "\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:381)\n",
      "\t... 9 more\n",
      "Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2832)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.chooseSocketFactory(RemoteTCPConnection.java:2593)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.makeSocketSecure(RemoteTCPConnection.java:2255)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.bindAndConnectSocket(RemoteTCPConnection.java:816)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.protocolConnect(RemoteTCPConnection.java:1381)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteConnection.connect(RemoteConnection.java:976)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getNewConnection(RemoteConnectionSpecification.java:553)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSessionFromNewConnection(RemoteConnectionSpecification.java:233)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSession(RemoteConnectionSpecification.java:141)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionPool.getSession(RemoteConnectionPool.java:127)\n",
      "\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13302)\n",
      "\t... 14 more\n",
      "Caused by: java.io.FileNotFoundException: /etc/opt/secrets/mq/clientkey.jks  (No such file or directory)\n",
      "\tat java.base/java.io.FileInputStream.open0(Native Method)\n",
      "\tat java.base/java.io.FileInputStream.open(FileInputStream.java:219)\n",
      "\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)\n",
      "\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)\n",
      "\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2765)\n",
      "\t... 24 more\n",
      "\n",
      "\"None None\"\n",
      "\n",
      "[thread_id 139663934713856] 2024-05-24 18:14:42,161 - utils.mq - CRITICAL - [Error 1] Unknown Exception when calling MQ Java.\n",
      "DEBUG - <class 'AssertionError'> ('utils.mq', \"failed to get connect or send message\\ncom.ibm.msg.client.jms.DetailedJMSException: JMSWMQ0018: Failed to connect to queue manager 'MQEXTT01' with connection mode 'Client' and host name 'externalmq-t0.ete.cathaypacific.com(1414)'.\\nCheck the queue manager is started and if running in client mode, check there is a listener running. Please see the linked exception for more information.\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)\\n\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:448)\\n\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)\\n\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)\\n\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)\\n\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createConnection(JmsConnectionFactoryImpl.java:236)\\n\\tat com.ibm.mq.jms.MQConnectionFactory.createCommonConnection(MQConnectionFactory.java:6005)\\n\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createQueueConnection(MQQueueConnectionFactory.java:136)\\n\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createConnection(MQQueueConnectionFactory.java:209)\\n\\tat JmsClient.connect(JmsClient.java:75)\\n\\tat Main.main(Main.java:36)\\nCaused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2393' ('MQRC_SSL_INITIALIZATION_ERROR').\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)\\n\\t... 10 more\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393;AMQ9204: Connection to host 'externalmq-t0.ete.cathaypacific.com(1414)' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2393],3=externalmq-t0.ete.cathaypacific.com(1414),5=RemoteTCPConnection.getNonFipsSocketFactory]\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13558)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1426)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1385)\\n\\tat com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377)\\n\\tat com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562)\\n\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:381)\\n\\t... 9 more\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2832)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.chooseSocketFactory(RemoteTCPConnection.java:2593)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.makeSocketSecure(RemoteTCPConnection.java:2255)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.bindAndConnectSocket(RemoteTCPConnection.java:816)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.protocolConnect(RemoteTCPConnection.java:1381)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnection.connect(RemoteConnection.java:976)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getNewConnection(RemoteConnectionSpecification.java:553)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSessionFromNewConnection(RemoteConnectionSpecification.java:233)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSession(RemoteConnectionSpecification.java:141)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionPool.getSession(RemoteConnectionPool.java:127)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13302)\\n\\t... 14 more\\nCaused by: java.io.FileNotFoundException: /etc/opt/secrets/mq/clientkey.jks  (No such file or directory)\\n\\tat java.base/java.io.FileInputStream.open0(Native Method)\\n\\tat java.base/java.io.FileInputStream.open(FileInputStream.java:219)\\n\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)\\n\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2765)\\n\\t... 24 more\\n\")\n",
      "\"<class 'AssertionError'> ('utils.mq', \"failed to get connect or send message\\ncom.ibm.msg.client.jms.DetailedJMSException: JMSWMQ0018: Failed to connect to queue manager 'MQEXTT01' with connection mode 'Client' and host name 'externalmq-t0.ete.cathaypacific.com(1414)'.\\nCheck the queue manager is started and if running in client mode, check there is a listener running. Please see the linked exception for more information.\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)\\n\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:448)\\n\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)\\n\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)\\n\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)\\n\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createConnection(JmsConnectionFactoryImpl.java:236)\\n\\tat com.ibm.mq.jms.MQConnectionFactory.createCommonConnection(MQConnectionFactory.java:6005)\\n\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createQueueConnection(MQQueueConnectionFactory.java:136)\\n\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createConnection(MQQueueConnectionFactory.java:209)\\n\\tat JmsClient.connect(JmsClient.java:75)\\n\\tat Main.main(Main.java:36)\\nCaused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2393' ('MQRC_SSL_INITIALIZATION_ERROR').\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)\\n\\t... 10 more\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393;AMQ9204: Connection to host 'externalmq-t0.ete.cathaypacific.com(1414)' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2393],3=externalmq-t0.ete.cathaypacific.com(1414),5=RemoteTCPConnection.getNonFipsSocketFactory]\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13558)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1426)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1385)\\n\\tat com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377)\\n\\tat com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562)\\n\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:381)\\n\\t... 9 more\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2832)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.chooseSocketFactory(RemoteTCPConnection.java:2593)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.makeSocketSecure(RemoteTCPConnection.java:2255)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.bindAndConnectSocket(RemoteTCPConnection.java:816)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.protocolConnect(RemoteTCPConnection.java:1381)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnection.connect(RemoteConnection.java:976)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getNewConnection(RemoteConnectionSpecification.java:553)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSessionFromNewConnection(RemoteConnectionSpecification.java:233)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSession(RemoteConnectionSpecification.java:141)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionPool.getSession(RemoteConnectionPool.java:127)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13302)\\n\\t... 14 more\\nCaused by: java.io.FileNotFoundException: /etc/opt/secrets/mq/clientkey.jks  (No such file or directory)\\n\\tat java.base/java.io.FileInputStream.open0(Native Method)\\n\\tat java.base/java.io.FileInputStream.open(FileInputStream.java:219)\\n\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)\\n\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2765)\\n\\t... 24 more\\n\")\"\n",
      "\n"
     ]
    },
    {
     "ename": "AssertionError",
     "evalue": "('utils.mq', '[Error 1] Unknown Exception when calling MQ Java.\\nDEBUG - <class \\'AssertionError\\'> (\\'utils.mq\\', \"failed to get connect or send message\\\\ncom.ibm.msg.client.jms.DetailedJMSException: JMSWMQ0018: Failed to connect to queue manager \\'MQEXTT01\\' with connection mode \\'Client\\' and host name \\'externalmq-t0.ete.cathaypacific.com(1414)\\'.\\\\nCheck the queue manager is started and if running in client mode, check there is a listener running. Please see the linked exception for more information.\\\\n\\\\tat com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)\\\\n\\\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)\\\\n\\\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:448)\\\\n\\\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)\\\\n\\\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)\\\\n\\\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)\\\\n\\\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createConnection(JmsConnectionFactoryImpl.java:236)\\\\n\\\\tat com.ibm.mq.jms.MQConnectionFactory.createCommonConnection(MQConnectionFactory.java:6005)\\\\n\\\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createQueueConnection(MQQueueConnectionFactory.java:136)\\\\n\\\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createConnection(MQQueueConnectionFactory.java:209)\\\\n\\\\tat JmsClient.connect(JmsClient.java:75)\\\\n\\\\tat Main.main(Main.java:36)\\\\nCaused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode \\'2\\' (\\'MQCC_FAILED\\') reason \\'2393\\' (\\'MQRC_SSL_INITIALIZATION_ERROR\\').\\\\n\\\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)\\\\n\\\\t... 10 more\\\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393;AMQ9204: Connection to host \\'externalmq-t0.ete.cathaypacific.com(1414)\\' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2393],3=externalmq-t0.ete.cathaypacific.com(1414),5=RemoteTCPConnection.getNonFipsSocketFactory]\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13558)\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1426)\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1385)\\\\n\\\\tat com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377)\\\\n\\\\tat com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562)\\\\n\\\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:381)\\\\n\\\\t... 9 more\\\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2832)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.chooseSocketFactory(RemoteTCPConnection.java:2593)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.makeSocketSecure(RemoteTCPConnection.java:2255)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.bindAndConnectSocket(RemoteTCPConnection.java:816)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.protocolConnect(RemoteTCPConnection.java:1381)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnection.connect(RemoteConnection.java:976)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getNewConnection(RemoteConnectionSpecification.java:553)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSessionFromNewConnection(RemoteConnectionSpecification.java:233)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSession(RemoteConnectionSpecification.java:141)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionPool.getSession(RemoteConnectionPool.java:127)\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13302)\\\\n\\\\t... 14 more\\\\nCaused by: java.io.FileNotFoundException: /etc/opt/secrets/mq/clientkey.jks  (No such file or directory)\\\\n\\\\tat java.base/java.io.FileInputStream.open0(Native Method)\\\\n\\\\tat java.base/java.io.FileInputStream.open(FileInputStream.java:219)\\\\n\\\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)\\\\n\\\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2765)\\\\n\\\\t... 24 more\\\\n\")')",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[0;32m~/connectivity-checker/utils/mq.py:263\u001b[0m, in \u001b[0;36mMQ.callback\u001b[0;34m(self, message_generation_time)\u001b[0m\n\u001b[1;32m    262\u001b[0m     LOG\u001b[38;5;241m.\u001b[39mcritical(error)\n\u001b[0;32m--> 263\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAssertionError\u001b[39;00m(\u001b[38;5;18m__name__\u001b[39m, error)\n\u001b[1;32m    265\u001b[0m LOG\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m==== [END] MQ Java Subprocess ====\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mAssertionError\u001b[0m: ('utils.mq', \"failed to get connect or send message\\ncom.ibm.msg.client.jms.DetailedJMSException: JMSWMQ0018: Failed to connect to queue manager 'MQEXTT01' with connection mode 'Client' and host name 'externalmq-t0.ete.cathaypacific.com(1414)'.\\nCheck the queue manager is started and if running in client mode, check there is a listener running. Please see the linked exception for more information.\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)\\n\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:448)\\n\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)\\n\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)\\n\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)\\n\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createConnection(JmsConnectionFactoryImpl.java:236)\\n\\tat com.ibm.mq.jms.MQConnectionFactory.createCommonConnection(MQConnectionFactory.java:6005)\\n\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createQueueConnection(MQQueueConnectionFactory.java:136)\\n\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createConnection(MQQueueConnectionFactory.java:209)\\n\\tat JmsClient.connect(JmsClient.java:75)\\n\\tat Main.main(Main.java:36)\\nCaused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2393' ('MQRC_SSL_INITIALIZATION_ERROR').\\n\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)\\n\\t... 10 more\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393;AMQ9204: Connection to host 'externalmq-t0.ete.cathaypacific.com(1414)' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2393],3=externalmq-t0.ete.cathaypacific.com(1414),5=RemoteTCPConnection.getNonFipsSocketFactory]\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13558)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1426)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1385)\\n\\tat com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377)\\n\\tat com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562)\\n\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:381)\\n\\t... 9 more\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2832)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.chooseSocketFactory(RemoteTCPConnection.java:2593)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.makeSocketSecure(RemoteTCPConnection.java:2255)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.bindAndConnectSocket(RemoteTCPConnection.java:816)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.protocolConnect(RemoteTCPConnection.java:1381)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnection.connect(RemoteConnection.java:976)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getNewConnection(RemoteConnectionSpecification.java:553)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSessionFromNewConnection(RemoteConnectionSpecification.java:233)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSession(RemoteConnectionSpecification.java:141)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionPool.getSession(RemoteConnectionPool.java:127)\\n\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13302)\\n\\t... 14 more\\nCaused by: java.io.FileNotFoundException: /etc/opt/secrets/mq/clientkey.jks  (No such file or directory)\\n\\tat java.base/java.io.FileInputStream.open0(Native Method)\\n\\tat java.base/java.io.FileInputStream.open(FileInputStream.java:219)\\n\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)\\n\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)\\n\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2765)\\n\\t... 24 more\\n\")",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mmq\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcallback\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/connectivity-checker/utils/mq.py:274\u001b[0m, in \u001b[0;36mMQ.callback\u001b[0;34m(self, message_generation_time)\u001b[0m\n\u001b[1;32m    272\u001b[0m     err_msg \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m[Error 1] Unknown Exception when calling MQ Java.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mDEBUG - \u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m+\u001b[39m \u001b[38;5;28mstr\u001b[39m(sys\u001b[38;5;241m.\u001b[39mexc_info()[\u001b[38;5;241m0\u001b[39m]) \u001b[38;5;241m+\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m \u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m+\u001b[39m \u001b[38;5;28mstr\u001b[39m(sys\u001b[38;5;241m.\u001b[39mexc_info()[\u001b[38;5;241m1\u001b[39m])\n\u001b[1;32m    273\u001b[0m     LOG\u001b[38;5;241m.\u001b[39mcritical(err_msg)\n\u001b[0;32m--> 274\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAssertionError\u001b[39;00m(\u001b[38;5;18m__name__\u001b[39m, err_msg)\n\u001b[1;32m    276\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__message_generation_time\n",
      "\u001b[0;31mAssertionError\u001b[0m: ('utils.mq', '[Error 1] Unknown Exception when calling MQ Java.\\nDEBUG - <class \\'AssertionError\\'> (\\'utils.mq\\', \"failed to get connect or send message\\\\ncom.ibm.msg.client.jms.DetailedJMSException: JMSWMQ0018: Failed to connect to queue manager \\'MQEXTT01\\' with connection mode \\'Client\\' and host name \\'externalmq-t0.ete.cathaypacific.com(1414)\\'.\\\\nCheck the queue manager is started and if running in client mode, check there is a listener running. Please see the linked exception for more information.\\\\n\\\\tat com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)\\\\n\\\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)\\\\n\\\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:448)\\\\n\\\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)\\\\n\\\\tat com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)\\\\n\\\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)\\\\n\\\\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createConnection(JmsConnectionFactoryImpl.java:236)\\\\n\\\\tat com.ibm.mq.jms.MQConnectionFactory.createCommonConnection(MQConnectionFactory.java:6005)\\\\n\\\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createQueueConnection(MQQueueConnectionFactory.java:136)\\\\n\\\\tat com.ibm.mq.jms.MQQueueConnectionFactory.createConnection(MQQueueConnectionFactory.java:209)\\\\n\\\\tat JmsClient.connect(JmsClient.java:75)\\\\n\\\\tat Main.main(Main.java:36)\\\\nCaused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode \\'2\\' (\\'MQCC_FAILED\\') reason \\'2393\\' (\\'MQRC_SSL_INITIALIZATION_ERROR\\').\\\\n\\\\tat com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)\\\\n\\\\t... 10 more\\\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393;AMQ9204: Connection to host \\'externalmq-t0.ete.cathaypacific.com(1414)\\' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2393],3=externalmq-t0.ete.cathaypacific.com(1414),5=RemoteTCPConnection.getNonFipsSocketFactory]\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13558)\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1426)\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1385)\\\\n\\\\tat com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377)\\\\n\\\\tat com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562)\\\\n\\\\tat com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:381)\\\\n\\\\t... 9 more\\\\nCaused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2393\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2832)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.chooseSocketFactory(RemoteTCPConnection.java:2593)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.makeSocketSecure(RemoteTCPConnection.java:2255)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.bindAndConnectSocket(RemoteTCPConnection.java:816)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.protocolConnect(RemoteTCPConnection.java:1381)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnection.connect(RemoteConnection.java:976)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getNewConnection(RemoteConnectionSpecification.java:553)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSessionFromNewConnection(RemoteConnectionSpecification.java:233)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionSpecification.getSession(RemoteConnectionSpecification.java:141)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteConnectionPool.getSession(RemoteConnectionPool.java:127)\\\\n\\\\tat com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13302)\\\\n\\\\t... 14 more\\\\nCaused by: java.io.FileNotFoundException: /etc/opt/secrets/mq/clientkey.jks  (No such file or directory)\\\\n\\\\tat java.base/java.io.FileInputStream.open0(Native Method)\\\\n\\\\tat java.base/java.io.FileInputStream.open(FileInputStream.java:219)\\\\n\\\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)\\\\n\\\\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)\\\\n\\\\tat com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.getNonFipsSocketFactory(RemoteTCPConnection.java:2765)\\\\n\\\\t... 24 more\\\\n\")')"
     ]
    }
   ],
   "source": [
    "mq.callback()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
